version: 2.1

orbs:
  python: circleci/python@1.4

workflows:
  upload_rhcos_ami:
    triggers:
      - schedule:
          cron: 0 9 * * *
          filters:
            branches:
              only:
                - main
    jobs:
      - upload-rhcos-ami-to-region:
          name: upload-rhcos-ami-to-us-gov-east-1
          aws_region: us-gov-east-1
          s3_bucket: rh-openshift-rhcos-govcloud-prod-vmimport-us-gov-east-1
          openshift_versions: 4.6 4.7 4.8 4.9
      - upload-rhcos-ami-to-region:
          name: upload-rhcos-ami-to-us-gov-west-1
          aws_region: us-gov-west-1
          s3_bucket: rh-openshift-rhcos-govcloud-prod-vmimport-us-gov-west-1
          openshift_versions: 4.6 4.7 4.8 4.9

jobs:
  upload-rhcos-ami-to-region:
    docker:
      - image: cimg/python:3.8
    parameters:
      aws_region:
        type: string
      s3_bucket:
        type: string
      openshift_versions:
        type: string
    environment:
      AWS_DEFAULT_REGION: << parameters.aws_region >>
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pipenv
      - run:
          name: Run script
          command: pipenv run python3 ./create_rhcos_ami.py --s3-bucket << parameters.s3_bucket >> --public << parameters.openshift_versions >>

